### Worker status
GET http://localhost:8000/status

### Query USDC transfers
POST http://localhost:8000/query/czM6Ly9ldGhhLW1haW5uZXQtc2lh
Content-Type: application/json
Accept-Encoding: gzip

{
  "fromBlock": 16143005,
  "fields": {
    "block": {
      "number": true,
      "hash": true,
      "parentHash": true
    },
    "log": {
      "data": true,
      "topics": true,
      "transaction": true
    },
    "transaction": {
      "from": true,
      "sighash": true
    }
  },
  "logs": [
    {
      "address": ["0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"],
      "topic0": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]
    }
  ]
}


### Deployed status 0
GET https://v2.archive.subsquid.io/worker/0/status

### Deployed status 1
GET https://v2.archive.subsquid.io/worker/1/status

###
POST https://v2.archive.subsquid.io/worker/0/query/czM6Ly9ldGhhLW1haW5uZXQtc2lh
Content-Type: application/json

{
  "fromBlock": 16000000,
  "logs": [
    {
      "address": ["0x3883f5e181fccaf8410fa61e12b59bad963fb645"]
    }
  ],
  "transactions": [],
  "fields": {
    "block": {
      "number": true,
      "hash": true,
      "parentHash": true,
      "nonce": true
    },
    "log": {
      "address": true,
      "topics": true,
      "data": true,
      "transaction": true
    },
    "transaction": {
      "to": true,
      "gas": true
    }
  }
}
