name: py-eth

channels:
  - conda-forge

dependencies:
   - fsspec
   - ipython
   - numpy
   - pandas
   - pip
   - pyarrow
   - pydantic
   - python=3.9
   - s3fs>=2021.8.0
   - pip:
      - duckdb
