[tool.poetry]
name = "subsquid-eth-archive"
description = "Subsquid stage 2 ingester and worker"
version = "0.1.0"
authors = ["Subsquid Labs GmbH <contact@subsquid.io>"]
readme = "README.md"
packages = [{include = "etha"}]

[tool.poetry.dependencies]
python = "^3.11"

duckdb = { version = "^0.7.1", optional = true }
falcon = { version = "^3.1", optional = true }
grpcio = { version = "^1.51", optional = true }
httpx = { version = "^0.23", optional = true }
marshmallow = "^3.19"
prometheus-client = { version = "^0.16", optional = true }
protobuf = { version = "^4.23", optional = true }
pyarrow = "^10.0"
s3fs = "^2021.8.0"
uvicorn = {version = "^0.17", optional = true }

[tool.poetry.extras]
p2p-worker = ["duckdb", "grpcio", "protobuf"]
http-worker = ["duckdb", "falcon", "httpx", "uvicorn"]
ingester = ["prometheus-client"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
