name: py-eth

channels:
  - conda-forge

dependencies:
  - aiofiles
  - falcon
  - fastparquet
  - fsspec
  - httpx
  - ipython
  - locust
  - numpy
  - pandas
  - pip
  - pyarrow
  - pydantic
  - python=3.11
  - s3fs>=2021.8.0
  - uvicorn
  - uvloop
  - yappi
  - pip:
      - duckdb
