name: py-eth

channels:
  - conda-forge

dependencies:
  - falcon
  - fastparquet
  - fsspec
  - httpx
  - ipython
  - locust
  - marshmallow
  - numpy
  - pandas
  - prometheus_client
  - pyarrow
  - pycryptodome
  - python-duckdb=0.7.1
  - python=3.11
  - s3fs>=2021.8.0
  - uvicorn
  - prometheus_client
