name: py-eth

channels:
  - conda-forge

dependencies:
  - falcon
  - fsspec
  - httpx
  - ipython
  - numpy
  - pandas
  - pip
  - pyarrow
  - pydantic
  - python=3.9
  - s3fs>=2021.8.0
  - uvicorn
  - pip:
      - duckdb
