# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\"\xc1\x02\n\x08\x45nvelope\x12\x1e\n\x04ping\x18\x01 \x01(\x0b\x32\x0e.messages.PingH\x00\x12-\n\x0cstate_update\x18\x02 \x01(\x0b\x32\x15.messages.WorkerStateH\x00\x12)\n\nget_worker\x18\x03 \x01(\x0b\x32\x13.messages.GetWorkerH\x00\x12\x36\n\x11get_worker_result\x18\x04 \x01(\x0b\x32\x19.messages.GetWorkerResultH\x00\x12 \n\x05query\x18\x05 \x01(\x0b\x32\x0f.messages.QueryH\x00\x12-\n\x0cquery_result\x18\x06 \x01(\x0b\x32\x15.messages.QueryResultH\x00\x12+\n\rdataset_state\x18\x07 \x01(\x0b\x32\x12.messages.RangeSetH\x00\x42\x05\n\x03msg\"#\n\x05Range\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\r\x12\x0b\n\x03\x65nd\x18\x02 \x01(\r\"+\n\x08RangeSet\x12\x1f\n\x06ranges\x18\x01 \x03(\x0b\x32\x0f.messages.Range\"\x89\x01\n\x0bWorkerState\x12\x35\n\x08\x64\x61tasets\x18\x01 \x03(\x0b\x32#.messages.WorkerState.DatasetsEntry\x1a\x43\n\rDatasetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.messages.RangeSet:\x02\x38\x01\"b\n\x04Ping\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x12\n\nworker_url\x18\x02 \x01(\t\x12$\n\x05state\x18\x03 \x01(\x0b\x32\x15.messages.WorkerState\x12\r\n\x05pause\x18\x04 \x01(\x08\"C\n\tGetWorker\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x13\n\x0bstart_block\x18\x03 \x01(\r\"S\n\x0fGetWorkerResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x13\n\tworker_id\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x42\x08\n\x06result\"9\n\x05Query\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\"k\n\x0bQueryResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x11\n\x07ok_data\x18\x02 \x01(\x0cH\x00\x12\x15\n\x0b\x62\x61\x64_request\x18\x03 \x01(\tH\x00\x12\x16\n\x0cserver_error\x18\x04 \x01(\tH\x00\x42\x08\n\x06resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKERSTATE_DATASETSENTRY._options = None
  _WORKERSTATE_DATASETSENTRY._serialized_options = b'8\001'
  _ENVELOPE._serialized_start=29
  _ENVELOPE._serialized_end=350
  _RANGE._serialized_start=352
  _RANGE._serialized_end=387
  _RANGESET._serialized_start=389
  _RANGESET._serialized_end=432
  _WORKERSTATE._serialized_start=435
  _WORKERSTATE._serialized_end=572
  _WORKERSTATE_DATASETSENTRY._serialized_start=505
  _WORKERSTATE_DATASETSENTRY._serialized_end=572
  _PING._serialized_start=574
  _PING._serialized_end=672
  _GETWORKER._serialized_start=674
  _GETWORKER._serialized_end=741
  _GETWORKERRESULT._serialized_start=743
  _GETWORKERRESULT._serialized_end=826
  _QUERY._serialized_start=828
  _QUERY._serialized_end=885
  _QUERYRESULT._serialized_start=887
  _QUERYRESULT._serialized_end=994
# @@protoc_insertion_point(module_scope)
