name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      target:
        description: target
        required: true
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: eldar
          password: ${{ secrets.ELDAR_DOCKER }}

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          target: ${{ inputs.target }}
          tags: eldar/sqa-${{ inputs.target }}:${{ inputs.tag }}
