name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      target:
        description: target
        required: true
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build . --target ${{ inputs.target }} -t "subsquid/test-etha-${{ inputs.target }}:${{ inputs.tag }}"

      - name: Publish
        run: docker publish subsquid/test-etha-${{ inputs.target }} --all-tags
